### ISSUE TITLE
add slate-only-in

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate-plugins#1]
And then deprecate use in the other plugins.

**Comment by Slapbox** [comment]
Hey Ian, I was wondering what considerations made you decide to drop `onlyIn` and `ignoreIn` for the autoreplace plugin. Performance, I'm guessing?

**Comment by Slapbox** [comment]
Oh. I guess probably because of this nifty plugin: https://github.com/ianstormtaylor/slate-plugins/tree/master/packages/slate-when

**Comment by ianstormtaylor** [comment]
This should be handled with plugin-specific queries now I think in the latest versions of slate, usually named `when` or something as an option.
