### ISSUE TITLE
gh-pages demo not rebuild with the newest slate

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate-plugins#12]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

The soft-break plugin demo is not rebuild with the merge_node->undo PR, like the following:

![](http://g.recordit.co/YJXcAot0f7.gif)

**Comment by ianstormtaylor** [comment]
Thanks, just rebuilt and published the GitHub pages.
