### ISSUE TITLE
Auto-replace Example Broken

### ISSUE THREAD

**Issue by wootencl** [ianstormtaylor/slate-plugins#24]
Looks like the auto replace example is borked. Tried to track down the issues myself to no avail 😞. Seems that `change` is not being passed in as an argument to the plugin for one reason or another. [Looks](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editor.js#L91) like it's being passed in taking a peak at `slate-react`'s source _but_ I'm also super new to the slate architecture so could be something obvious going wrong elsewhere. 

/cc @ianstormtaylor

**Comment by wrobbinz** [comment]
Ran into this as well. Just wanted to call out that it's broken on the demo page as well: https://ianstormtaylor.github.io/slate-plugins/#/slate-auto-replace

**Comment by MustafaFaris** [comment]
I've tracked down the problem to this commit :

https://github.com/ianstormtaylor/slate-plugins/commit/ddfc5e91a09f3c8d15cdcd713550731ed2398fda#diff-381f85095197bcecc10eb6424caa4281

Seems like @ianstormtaylor have changed the `transform` parameter to `change` in `index.js`. However, for some reasons he forgot to update the Auto-Replace demo. 

so the following should work :

```
 plugins = [
    AutoReplace({
      trigger: ')',
      before: /(\(c)$/i,
      change: transform => transform.insertText('©')
    }),
]
```
