### ISSUE TITLE
Question regarding Undo History with Slate-Auto-Replace

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate-plugins#9]
It seems that Slate-Auto-Replace removes each capture group in a separate operation, which means if a user tries to undo it, they actually have to undo each operation one at a time. Is there a reasonably easy way to undo all the changes with a single undo?

Thanks for a millionth time Ian.

**Comment by CameronAckermanSEL** [comment]
@Slapbox there should be a `change.setOperationsFlag('merge', true)` operation you can use to get those changes applied to the same `undo` operations list on the top of the undo stack

**Comment by Slapbox** [comment]
For anyone looking, the method would now be to wrap your changes inside of:

```js
change.withoutNormalizing(() => {
  //  Your changes
})
```
